### ISSUE TITLE
the upload component can't work in latest vaddin 12.0.0

### ISSUE THREAD

**Issue by jessyZu** [vaadin/vaadin-upload-flow#103]
when upgrade to 12.0.0,the upload component can't listen the event.
code:
```

 MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
        upload.setReceiver(buffer);
        upload.setAcceptedFileTypes("image/jpeg", "image/png", "image/gif", "image/jpg");
        upload.addSucceededListener(event -> {
            try {
                String imgName = MD5Util.md5(UUID.randomUUID().toString()) + "." + event.getFileName().split("\\.")[1];
                FileUtils.writeByteArrayToFile(new File("/statics/imgs/" + imgName),
                        IOUtils.toByteArray(buffer.getInputStream(event.getFileName())));
                getModel().getImgs().add(imgName);

            } catch (Exception e) {
                getLogger().error("upload error", e);
                showNotification("图片保存失败："+e.getMessage(),true);

            }
        });


```

**Comment by heruan** [comment]
@jessyZu Are you using Spring? If so, probably related to https://github.com/vaadin/spring/issues/381

**Comment by limonte** [comment]
from @benderfzi (https://github.com/vaadin/vaadin-upload-flow/issues/104#issuecomment-445764808)

[Bender-Vaadin12-Spring-Issue-104.zip](https://github.com/vaadin/vaadin-upload-flow/files/2662673/Bender-Vaadin12-Spring-Issue-104.zip)

Attached minimum example as Eclipse Maven project which reproduces the error with Spring Boot and Vaadin 12.

**Comment by jessyZu** [comment]
@heruan ,yes,I use Spring . After set spring.servlet.multipart.enabled=false,it works fine.

**Comment by zapphyre** [comment]
does not fixes for me. either way, I need multipart upload support in the app.
