### ISSUE TITLE
Calling MultiFileMemoryBuffer .getFiles().clear() causes corruption of uploaded items.

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-upload-flow#118]
I'm still investigating why this happens but it seems that calling getFiles().clear() inside of  addSucceededListener seems to cause corruption on uploads.

Could it be that the listner method is called when the items are still being written to disk and when i clear the buffer it causes the corruption? If so - is there a different listener which is only called when it is safe to clear the buffer for a new upload?

**Comment by denis-anisimov** [comment]
Could you please provide a code which can be used for test?
You can use https://github.com/vaadin/skeleton-starter-flow/ as a base for that.

**Comment by masbaehr** [comment]
Actually i've reviewed this, and probably it can be closed, since i was writing the file to disk in the addSucceededListener , and did call  buffer.getFiles().clear(); here. But probably i've should implement it myself to wait for when the method which writes to disk has actually finished. 
However i don't understand why this happens, as i'm passing the byte as array to the method which does the writing. How come it interferes with the bytes already "passed" :/

```java
MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
		Upload uploadComponent = new Upload(buffer);		
		uploadComponent.setId("my-upload-component");
		uploadComponent.setUploadButton(new Button("Upload documents", new Icon(VaadinIcon.UPLOAD)));
		uploadComponent.setDropLabel(new Span("or use Drag&Drop!"));
		uploadComponent.setDropLabelIcon(new Icon(VaadinIcon.AREA_SELECT));
		uploadComponent.addSucceededListener(event -> {
            
			 for(String fileName : buffer.getFiles()){
				ByteArrayOutputStream os = (ByteArrayOutputStream) buffer.getFileData(fileName).getOutputBuffer();
				byte[] bytes = os.toByteArray();
				FileEngine.saveFile("myPath", fileName, bytes);
            }
            buffer.getFiles().clear();//This call causes corruption on some of the uploaded files. (Use 20 items with equal size to increase the chance of happening, so it can be seen quickly in the OS explorer)
            UI.getCurrent().getPage().executeJavaScript("document.getElementById(\"my-upload-component\").files = []");
            
       });
```
