### ISSUE TITLE
Disabled Upload Button still able to upload

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/vaadin-upload-flow#121]
I have the need to disable the Upload when certain conditions are met. Since the Upload itself does not implement `HasEnabled`, I disabled the underlying Button that was set using `upload.setUploadButton(button)`. 

The result of this is a **visually disabled** upload button, but when clicked anyway the file chooser popup still appeared. When I selected a file there, the succeededListener of the upload was triggered and the file was uploaded.
This is not supposed to happen. 

Hiding the Upload button instead of disabling it is not an option for me.  I still need it to be displayed but not to be functional. 

What I need is no opening of the file chooser popup when a disabled upload-button is clicked. It would also be nice to be able to call `setEnabled(false);` on the upload directly and not its underlying button but this is not that important.

Minimal example for reproduction:
```
@Route
public class MainView extends VerticalLayout {
    public TestView(){
        Upload upload = new Upload(new MultiFileMemoryBuffer());
        upload.setDropAllowed(false);
        Button uploadButton = new Button("Upload", VaadinIcon.UPLOAD.create());
        upload.setUploadButton(uploadButton);

        upload.addSucceededListener(event -> {
            Notification.show("SucceededEvent was fired, upload starting");
        });

        Button disableUploadButton = new Button("Toggle disabled status of Upload", VaadinIcon.RETWEET.create(), click -> {
            uploadButton.setEnabled(!uploadButton.isEnabled());
        });

        add(disableUploadButton, upload);
    }
}
```

**Comment by ZheSun88** [comment]
Hi, 
I have seen your post in the vaadin forum, https://vaadin.com/forum/thread/17509754/17509755 

Currently, this feature is not supported, but as a workaround, you can `upload.setMaxFiles(0)`  to achieve it. 

you can following this issue https://github.com/vaadin/vaadin-upload/issues/146 and vote to this feature. 

I am closing this ticket now.
