### ISSUE TITLE
Method setUploadButton() works differently as documented

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-upload-flow#122]
**Vaadin Upload Flow Version 1.3.0**
The javadoc of the method `setUploadButton()` says "_Set the component as the actionable button inside the upload component, that starts the upload of the selected files._", but in fact the button sent as a parameter will open the dialog for choosing the files to be upload, and not start the actual upload of them (for example if `setAutoUpload(false)` is called previously).

**Comment by TatuLund** [comment]
Furthermore it says "the component to be clicked by the user to start the upload, or null to clear it", but using null does not remove the button.

**Comment by TatuLund** [comment]
To fix the later problem, one can use the following theme module as workaround:

<dom-module id="upload-without-button" theme-for="vaadin-upload-file">
<template>
<style>
:host(.upload-without-button) [part="start-button"] {
display: none;
}
</style>
</template>
</dom-module>
