### ISSUE TITLE
Copy-pasting examples as it will not compile due to helper methods

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-upload-flow#124]
It would be really nice to have more documentation for the Upload component. Now there is only two small code snippets at https://vaadin.com/docs/flow/components/tutorial-flow-upload.html

**Comment by web-padawan** [comment]
The component examples are here: https://vaadin.com/components/vaadin-upload/java-examples

@anasmi is this issue still valid? Would you have any suggestions for actual improvements?

**Comment by anasmi** [comment]
Thanks for reacting to it! 
I would appreciate an added `showOutput` method in the examples, at least. Know copy-pasting them as it will not compile.

**Comment by web-padawan** [comment]
See also https://vaadin.com/forum/thread/18119388/upload-component-clarification

User was confused about `createComponent` in demo:
https://github.com/vaadin/vaadin-upload-flow/blob/c6e8e7de394c7fc1682ef3c64943a2cd116dfedd/vaadin-upload-flow-demo/src/main/java/com/vaadin/flow/component/upload/demo/UploadView.java#L267

**Comment by web-padawan** [comment]
Fixed by #164 which was merged to `2.1` branch and is also present in `2.2`. Closing.
