### ISSUE TITLE
No event for when all files have finished uploading.

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/vaadin-upload-flow#134]
The Upload has many events that trigger upon status changes of single files, but there is no event triggered when *all* files are finished. This is a very important Event, as I can only start my background Thread once all files are finished uploading. Since the Upload Component supports multi file upload, such an event is a must have. As long as it doesnt exist, I could just as well restrict the upload file count to 1. (I know that there are usecases where an action could be taken for each single file, but that is not the case for me. I need all the files at once, and cannot start to import the first without having the last.)

I could also check in the SucceededListener each time a single file was uploaded successfully, if that file was the last file, but the SucceededEvent has no information whether it was the last file. 

What I am doing now to workaround this issue is this:
I add a NumberField Component next to the Upload, where the user *must* enter the amount of files they want to upload. Now that I know how many files I must expect, I can check within the SucceededListener if it is the last file by increment an index each time the listener runs and compare that index with the user-input in the NumberField. If they are the same, it was the last file and I can start my background Thread.

Here is the code of my workaround:

```
@Route("Upload")
public class UploadView extends VerticalLayout {
    private static final Logger LOGGER = LogManager.getLogger(TestView.class);

    private MultiFileMemoryBuffer buffer = new MultiFileMemoryBuffer();
    private final int MAX_FILE_UPLOADS = 10;
    private Set<UploadPojo> unprocessedUploads = new HashSet<>();
    private Integer uploadedFilesIndex = 0;

    public UploadView(){
        NumberField uploadsCount = new NumberField(getTranslation("HowManyFiles"));
        uploadsCount.setHasControls(true);
        uploadsCount.setValue(1d);
        uploadsCount.setWidth("100%");

        Upload uploadBtn = new Upload(buffer);
        uploadBtn.setWidth("100%");
        uploadBtn.setAcceptedFileTypes(".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        uploadBtn.setMaxFiles(MAX_FILE_UPLOADS);
        uploadBtn.setDropAllowed(false);
        Button actualReuploadButton = new Button(getTranslation("import"), VaadinIcon.UPLOAD.create());
        actualReuploadButton.setWidth("100%");
        uploadBtn.setUploadButton(actualReuploadButton);

        uploadBtn.addSucceededListener(event -> {
            File file = null;
            try {
                file = File.createTempFile("tmp_file_upload", null);
                FileUtils.copyInputStreamToFile(buffer.getInputStream(event.getFileName()), file);
            } catch (IOException e) {
                LOGGER.error(e.getMessage(), e);
            }
            unprocessedUploads.add(new UploadPojo(file, event.getFileName(), event.getMIMEType(), event.getContentLength()));
            uploadedFilesIndex++;
            if (uploadedFilesIndex.equals(uploadsCount.getValue().intValue())) {
                LOGGER.debug(String.format("starting import - uploaded %d / %s%n", uploadedFilesIndex, uploadsCount.getValue()));
                importAllUnprocessedUploads();
            } else {
                LOGGER.debug(String.format("skipping import - uploaded %d / %s%n", uploadedFilesIndex, uploadsCount.getValue()));
            }
        });

        // check if value is between 1 and maxFiles. and enable/disable the upload button accordingly
        uploadsCount.addValueChangeListener(change -> {
            // Disabling upload by setting max files to 0 AND disabling underlying button
            // https://vaadin.com/forum/thread/17509754/17509755
            int uploadsCountValue = change.getValue().intValue();
            boolean isUploadEnabled = uploadsCountValue > 0 && uploadsCountValue <= MAX_FILE_UPLOADS;
            uploadBtn.setMaxFiles(isUploadEnabled ? MAX_FILE_UPLOADS : 0);
            actualReuploadButton.setEnabled(isUploadEnabled);
        });

        HorizontalLayout uploadLayout = new HorizontalLayout(uploadsCount, uploadBtn);
        uploadLayout.setWidth("100%");
        uploadLayout.getStyle().set("border", "1px solid var(--lumo-primary-color)");
        uploadLayout.setDefaultVerticalComponentAlignment(Alignment.END);
        add(uploadLayout);
    }

    /**
     * When this is called, all uploads are finished. They are stored in unprocessedUploads.
     */
    private void importAllUnprocessedUploads() {
        uploadedFilesIndex = 0; // reset index to 0

        // start background thread here.
        LOGGER.debug("Starting import now");
    }
}
public class UploadPojo {

    private File file;
    private String fileName;
    private String mimeType;
    private long length;

    public UploadPojo(File stream, String fileName, String mimeType, long length) {
        this.file = stream;
        this.fileName = fileName;
        this.mimeType = mimeType;
        this.length = length;
    }
    // getters & setters omitted
}
```

**Comment by vladimirdyuzhev** [comment]
Have the same issue - I need to upload WSDL and a number of related XSD files. Starting processing before all of them are uploaded will cause a failed validation. The Upload component tho gives me no indication if the just uploaded file is the last one. 

I'm planning to add a delay of a second or so after each completed upload, and check the isUploading() value. If it is still false, then no new uploads started and so the list is exhausted. This workaround is ugly tho because it takes starting a thread. I'm also not sure how reliable it is.

**Comment by tomivirkki** [comment]
Hi, I tried the attached code snippet. Is there a need for a separate event for this? Wouldn't the following do the trick?

```js
uploadBtn.addFinishedListener(event -> {
  if (!uploadBtn.isUploading()) {
    System.out.println("All done");
  }
}
```

**Comment by KasparScherrer** [comment]
Hi. Wow, yes somehow I must have overlooked the `isUploading` method of the `Upload` class. This is embarassing 😢 

I will test your suggestion tomorrow and will report back here. I just want to be 100% sure that there is e.g. not a race-condition happening on the `activeUploads` variable that the isUploading method uses :)

**Comment by KasparScherrer** [comment]
I have now tried this, and sadly it does not work.

When I use it in a `FinishedListener`, the condition `if(!uploadBtn.isUploading())` returns true way too early and therefore starts my batch import process multiple times. It usually thinks it has finished uploading after every single file. I have seen the condition return false only once, and it was seemingly random.

When I use it in a `SucceededListener`, the condition is never true. It leads me to believe that within a succededListener the isUploading method will always return true.

**Comment by tomivirkki** [comment]
Feels like it _should_ work like that though. Looking at the code of `Upload`, it increases the value of `activeUploads` when new upload starts and decreased when one finishes. `isUploading()` returns `false` iff `activeUploads` is 0.

If it doesn't, it might be a bug somewhere in the component. I'll take another look at this next week.

**Comment by tomivirkki** [comment]
Looks like occasionally uploads might finish while there are other files in the queue that haven't yet started uploading. A dedicated event that dispatches when the whole queue is complete would be in order indeed.

Meanwhile, you could try the following workaround. It observes changes to the "files" array of the element and prints when all the files in the array are "complete".

```java
upload.getElement().addEventListener("files-changed", e -> {
    JsonArray files = e.getEventData().getArray("element.files");

    boolean _allUploadsProcessed = true;
    for (int i = 0; i < files.length(); i++) {
        JsonObject file = files.getObject(i);
        if (!file.getBoolean("complete")) {
            _allUploadsProcessed = false;
        }
    }

    if (!this.allUploadsProcessed && _allUploadsProcessed
            && files.length() > 0) {
        System.out.println("All done");
    }
    this.allUploadsProcessed = _allUploadsProcessed;
}).addEventData("element.files");
```
