### ISSUE TITLE
Uploaded file does not have original file name (Spring Boot, multipart)

### ISSUE THREAD

**Issue by DnlGDev** [vaadin/vaadin-upload-flow#142]
The uploaded file always has file name **"file"** on server side e.g. in SucceededEvent. 

`upload.addSucceededListener(e -> e.getFileName());`

This only occurs in combination with Spring Boot. 
If I set `spring.servlet.multipart.enabled = false` I get the original file name. 

Unfortunately I cannot disable the multipart featue of Spring. Can anyone help with a workaround?

----

SpringBoot: 2.1.6.RELEASE
Vaadin: 13.0.10

**Comment by dawiemalan** [comment]
StreamReceiverHandler:237 should be:
`String name = part.getSubmittedFileName();`

**Comment by bastianlemke** [comment]
MultiFileMemoryBuffer does not work because of this issue ... the file name is used as key for the FileData map.

**Comment by peholmst** [comment]
I just created a PR to fix this issue. I've been on vacation for four weeks, hence the delay.

**Comment by javier-godoy** [comment]
@peholmst Please apply the fix to flow-server:1.4

**Comment by peholmst** [comment]
Pull request created for 1.4.
