### ISSUE TITLE
As a developer I want to be able to prevent the upload from displaying the file stack

### ISSUE THREAD

**Issue by paulroemer** [vaadin/vaadin-upload-flow#32]
With the element API you can already access the `files` property to empty it after a successful upload:

```upload.getElement().setPropertyJson("files", Json.createArray());```

But from a DX point of view it might sense to extend the API by some flag that allows the developer to disable displaying the stack at all.

Another option would be to disable the file stack whenever maxFiles == 1.

**Comment by web-padawan** [comment]
> access the files property to empty it

Also requested at #96 

> disable displaying the stack at all.

Also requested at #56

Closing in favor of those issues.
