### ISSUE TITLE
(TypeError) : Cannot read property 'c' of undefined

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-upload-flow#51]
With RC1 Platform BOM a simple `Upload` component throws this client error:

```
(TypeError) : Cannot read property 'c' of undefined
```

Simple component to replicate (as in https://github.com/heruan/flow-test/tree/upload-undefined):

```java
@Route("")
public class FileUpload extends Div {

    public FileUpload() {
        Upload upload = new Upload((name, type) -> {
            return new ByteArrayOutputStream();
        });
        this.add(upload);
    }

}
```

**Comment by heruan** [comment]
@ZheSun88 Are you able to reproduce this? I've seen RC2 was released, so I guess this is not as blocking as it seems. Maybe it's just me with broken deps?

**Comment by ZheSun88** [comment]
@heruan Yes, i still can reproduce this.. as this issue is causing by the commit which changing the flow client side.

**Comment by heruan** [comment]
I don't understand "as this issues is causing by the commit which changing the flow client side". Are saying this will be implicitly fixed by updating to RC2 due to dependencies update?

**Comment by ZheSun88** [comment]
I mean this error occurs after we got this commit https://github.com/vaadin/flow/commit/888ffd6d4fadfdc5e2f880f61d54673affd818bd

**Comment by heruan** [comment]
Thank you for the commit reference, @ZheSun88! Still I don't get why RC2 of this component was released being unusable 😕

**Comment by ZheSun88** [comment]
In RC2, we have fixed some other bugs related to the I18n object. But we haven't detected the issue you have reported. I am fixing it now, and if possible, i will make it to the platform. 

That is very sorry, it looks we don't have an test case to check this, either.

**Comment by ZheSun88** [comment]
Now the problem has been fixed. @heruan it will be shipped with next flow release

**Comment by iatomic** [comment]
I am still haveing the same exact problem with Vaadin 10. on very device I get Type erroc cannot read property ...sometimes property 0 sometimes 1 or 2... what is the solution in the end in terms of version I should use. I use 	<vaadin.version>11.0.0</vaadin.version> do I need anything more?

**Comment by iatomic** [comment]
<vaadin.version>11.0.0</vaadin.version>
		<vaadin.version>1.1.0.beta4</vaadin.version>

		<dependency>
		    <groupId>com.vaadin</groupId>
		    <artifactId>vaadin-upload-flow</artifactId>
		    <version>${component.version}</version>
		</dependency>


still same problem....TypeError: Cannot read property '1' of undefined
