### ISSUE TITLE
Localization leads to javascript error

### ISSUE THREAD

**Issue by JonasManuelKonstruktum** [vaadin/vaadin-upload-flow#67]
Hi we are creating an upload and set a our i18n properties:
`Upload upload = new Upload();
upload.setI18n(new UploadI18N()
				.setDropFiles(new UploadI18N.DropFiles().setOne("Datei hierher ziehen...")
						.setMany("Dateien hierher ziehen..."))
				.setAddFiles(new UploadI18N.AddFiles().setOne("Datei auswählen...").setMany("Dateien auswählen..."))
				.setCancel("Abbrechen")
				.setError(new UploadI18N.Error().setTooManyFiles("Zu viele Dateien.")
						.setFileIsTooBig("Datei ist zu groß.").setIncorrectFileType("Falscher Dateityp."))
				.setUploading(new UploadI18N.Uploading()
						.setStatus(new UploadI18N.Uploading.Status().setConnecting("Verbinden...")
								.setStalled("Blockiert...").setProcessing("Verarbeitung..."))
						.setRemainingTime(new UploadI18N.Uploading.RemainingTime().setPrefix("Verbleibende Zeit: ")
								.setUnknown("Unbekannte Zeit"))
						.setError(new UploadI18N.Uploading.Error().setServerUnavailable("Server nicht verfügbar.")
								.setUnexpectedServerError("Unerwarteter Serverfehler.")
								.setForbidden("Verbotenener Vorgang.")))
				.setUnits(Arrays.asList("Bytes", "KB", "MB", "GB", "TB", "PB", "EB")));`

when we deploy the application, while uploading bigger files, the component throws a lot of errors when trying to show the upload progress.

As far as I can see these are coming from the following line:
`l.408           return size + ' ' + this.i18n.units.size[unit]; `
if I leave out the I18n everything works fine..

**Comment by JonasManuelKonstruktum** [comment]
this should be fixed by saying
`return size + ' ' + this.i18n.units[unit];` instead

**Comment by xingxiuyi** [comment]
UploadI18N.units should be Map<String, List<String>>, not List<String>.

Or define a Units class has size property?

**Comment by gilberto-torrezan** [comment]
Thank you @xingxiuyi for the contribution!

Also, pro-tip: when a reviewer asks for a change in your pull request, you don't need to close it and create a new one - you can just make the change and push it to the same branch. The PR is automatically updated with the new revision, and the reviewer is notified about the changes.

That makes it easier for you to make the changes, and easier for us to review and keep track of what has been changed in which revision ;-)
