### ISSUE TITLE
The two first Java upload examples are missing the source code

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/vaadin-upload-flow#70]
From Gitlab. By Artur. 
--
https://vaadin.com/elements/vaadin-upload/java-examples

There is no description and no source code for the first two demos. What do they do? How do they work? What do they show?

**Comment by ZheSun88** [comment]
This issue has been fixed, as you can check the source code from https://vaadin.com/components/vaadin-upload/java-examples

issue closed
