### ISSUE TITLE
Upload Java example is confusing

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-upload-flow#72]
From Gitlab. By Artur.
--
https://vaadin.com/elements/vaadin-upload/java-examples

If you upload a large file, nothing happens

If you upload e.g. a jar file, the example shows

[checkmark] artifacts.jar

artifacts.jar
If you "delete" the upload file, one of the "artifact.jar" texts remain on screen

If you upload a large image, the whole layout "explodes"

**Comment by web-padawan** [comment]
Fixed by #174
