### ISSUE TITLE
FinishedListener is never called

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-upload-flow#77]
```
        Upload upload = new Upload((MultiFileReceiver) (filename, mimeType) -> {
            File file = new File(new File("uploaded-files"), filename);
            try {
                return new FileOutputStream(file);
            } catch (FileNotFoundException e1) {
                e1.printStackTrace();
                return null;
            }
        });
        upload.addStartedListener(e -> {
            System.out.println("Handling upload of " + e.getFileName() + " ("
                    + e.getContentLength() + " bytes) started");
        });
        upload.addFinishedListener(e -> {
            System.out.println("Handling upload of " + e.getFileName() + " ("
                    + e.getContentLength() + " bytes) finished");
        });

        add(upload);
```

Only prints `started` messages and never `finished` messages

**Comment by ttsanton** [comment]
Hello, I'm encountering the same issue with all three (Started/Finished/Succeeded) Listeners. They are not called when an upload is being submitted.  I am currently using the Started/Finished Listeners to verify an image upload is being made and a Succeeded Listener to return a preview of the image.

It also appears that the MemoryBuffer, even though set to the Upload when initialized, is returning a null/empty value.

**Comment by ttsanton** [comment]
I also want to confirm that this is still an issue in 13.0.0.alpha1

**Comment by Silver-Wulf** [comment]
I had thought this was an issue with the event not being called but it is actually that the SucceedEvent and FailedEvent should be caught by the listener targeting their superclass, FinishedEvent, and is not. This seems to be an issue in the event bus itself and how it compares classes.

**Comment by KrifaYounes** [comment]
how to fix that on vaadin10.0.11 ?

**Comment by KrifaYounes** [comment]
can you release a vaadin10.0.12 with the fix please ?
