### ISSUE TITLE
can we make it SIMPLE

### ISSUE THREAD

**Issue by iatomic** [vaadin/vaadin-upload-flow#78]
.1 we want to have a dir where files will be put
2. we want to be notified when a file is removed and I want t have the file removed....

delphi super simplicity... I wish we had it in vaadin

**Comment by mstahv** [comment]
Created https://github.com/vaadin/vaadin-upload-flow/issues/96 for the second part of wish number 2. File removing listeners already covered in https://github.com/vaadin/vaadin-upload-flow/issues/63

**Comment by web-padawan** [comment]
Looks like wish number 2 is covered and wish number 1. sounds rather unclear to me.

If you'd like to request a feature, please create another issue with a more detailed description of what new functionality are you expecting from a component and what is your use case.

As long as the issue says "can we make it SIMPLE", it actually means our docs are not great.

Closing in favor of #124 where we are discussing documentation improvements.
