### ISSUE TITLE
SERIOUS upload-flow issues making it unfit for production

### ISSUE THREAD

**Issue by iatomic** [vaadin/vaadin-upload-flow#93]
this thread is NOT for FEATURES (add remove etc) but for fixing BASIC FUNDAMENTAL usability of this component that is MISSES. Please lets try NOT TO move it under unrelated issues that are FEATURES people would like to have (one example add-remove - there are workarounds).

Could we try to fix the Upload component as even though we got it to work it is throwing exceptions
on the client side to the point that it scares users so bad that we may have to entirely remove it from use as totally unfit for production. Any idea how to choke JS exceptions it is throwing (how to get them choked those exception popups are trully ANNOYING)? see images below. upload works but it keeps still throwing exceptions ruin any decent/acceptable user experience. see below images.

![terror](https://user-images.githubusercontent.com/42481030/48072563-1a4bd700-e1dd-11e8-8de0-9d6d1df22bc0.png)
![upload-error](https://user-images.githubusercontent.com/42481030/48072566-1ddf5e00-e1dd-11e8-92c8-4889995c4968.png)

**Comment by heruan** [comment]
Hello @iatomic, I suggest trying to avoid assumptions about a component being broken if you are experiencing issues with it, as it might be a side effect of how the component is being used. For example, I'm using the same component in different scenarios and I have no exceptions at all.

About your issue, are you running in production mode? [1] When in production mode, most client-side exception do not "popup" (which seems exactly what you're asking for).

Also, I *strongly* suggest you to provide a minimal application which replicates your issue; this way, the team will be able to identify what is causing it and provide a solution much faster.

- [1] https://vaadin.com/docs/v11/flow/production/tutorial-production-mode-basic.html

**Comment by iatomic** [comment]
it turned out the issues we have faced were caused by UploadI18N not Upload. We removed UploadI18N , no more issues
