### ISSUE TITLE
Vaadin is running in DEBUG MODE. Add productionMode=true to web.xml to disable debug features.

### ISSUE THREAD

**Issue by iatomic** [vaadin/vaadin-upload-flow#94]
all over the place I see .. set vaadin.servlet.productionMode

I set it and it does  not work.  what is it that is supposed to be set ?
vaadin.servlet.productionMode?
or just productionMode?

as servlet parameter? on what servlet? or just in web.xml?

to pom I added in the end flow-server-production-mode and commented out flow-server.
it turns out Meta tag classes that we use are missing in flow-server-production vs flow-server....

			<dependency>
			    <groupId>com.vaadin</groupId>
			    <artifactId>flow-server-production-mode</artifactId>
			    <version>1.2.0</version>
			</dependency>
			<dependency>
			    <groupId>com.vaadin</groupId>
			    <artifactId>flow-server</artifactId>
			    <version>1.2.0</version>
			</dependency>

			<dependency>
			  <groupId>com.vaadin</groupId>
			  <artifactId>flow-client</artifactId>
			    <version>1.2.0</version>
			</dependency>		

can anyone document it for example for spring boot?

I also tried in aplication.properties on the classpath

#vaadin.servlet.resourceCacheTime
vaadin.servlet.productionMode=true
#vaadin.servlet.heartbeatInterval
vaadin.servlet.closeIdleSessions=true;

all else works but for productionMode of vaadin....

**Comment by elmot** [comment]
Looks like you have run into Vaadin 8 documentation 
For Vaadin 10+ see https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html

**Comment by iatomic** [comment]
We got a tiny problem with it. We need 

@Meta tag (to mark web page language etc)

When we include

			<dependency>
			    <groupId>com.vaadin</groupId>
			    <artifactId>flow-server-production-mode</artifactId>
			    <version>1.2.0</version>
			</dependency>
	
we get ERRORS that @Meta is Missing

when we include  non production as below, it is working
		<dependency>
			    <groupId>com.vaadin</groupId>
			    <artifactId>flow-server</artifactId>
			    <version>1.2.0</version>
			</dependency>


Caused by: java.lang.Error: Unresolved compilation problems:
        The import com.vaadin.flow.component.page.Meta cannot be resolved
        Meta cannot be resolved to a type
        Meta cannot be resolved to a type

**Comment by iatomic** [comment]
Actually, now that we EXCLUDED older vaadin-server from spring-boot and keep vaadin-server 1.2, we are getting exceptions that it cannot find vaadin servlet...

**Comment by iatomic** [comment]
<profiles>
    <profile>
        <id>productionMode</id>
        <dependencies>            
 			<dependency>
			    <groupId>com.vaadin</groupId>
			    <artifactId>flow-server-production-mode</artifactId>
			</dependency>
        </dependencies>
        <build>
            <plugins>
                <plugin>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin-maven-plugin</artifactId>
                    <version>${vaadin.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>copy-production-files</goal>
                                <goal>package-for-production</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>             
				<plugin>
				    <groupId>org.eclipse.jetty</groupId>
				    <artifactId>jetty-maven-plugin</artifactId>
				    <version>${jetty.version}</version>
				    <configuration>
				        <webAppConfig>
				            <resourceBases>
				                <resourceBase>${transpilation.output}</resourceBase>
				            </resourceBases>
				        </webAppConfig>
				    </configuration>
				</plugin>                
                
            </plugins>
        </build>
    </profile>
</profiles>

and we land up with 
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:11.0.1:package-for-production (default) on project ROOT: Execution default of goal com.vaadin:vaadin-maven-plugin:11.0.1:package-for-production failed: Failed to load class 'com.vaadin.flow.component.dependency.StyleSheet' in custom classloader -> [Help 1]

**Comment by iatomic** [comment]
it does not seem to work. 

flow-server-production-mode is just an empy jar with web fragment that sets 
```
    <context-param>
        <param-name>productionMode</param-name> 
        <param-value>true</param-value>      
    </context-param>
```

the war we generate with mvn does have web.xml that has this parameter set.
Since we use spring-boot we also added to application.properties

`server.context_parameters.productionMode=true `

this is also supposed to set this context parameter for VAADIN servlet

on top of this we used in spring-boot
```
public class Starter extends SpringBootServletInitializer {
...
	   @Override
	    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
	        return application.sources(Starter.class);
	    }

	    @Override
	    public void onStartup(ServletContext servletContext) throws ServletException {
	        servletContext.setInitParameter("productionMode", "true");
	        super.onStartup(servletContext);
	    }	
..}

```	

and it still does not work...I will not mention we did all the tutorial mentions...
any ideas?

**Comment by caalador** [comment]
As a System parameter it would be `vaadin.productionMode` but as a servlet initParameter it should just be `productionMode`.

For a Spring-Boot sample you could have a look at the [Project Base with Spring](https://vaadin.com/start/lts/project-base-spring) which will work in development mode when building a default war, but work fine in production mode when building with the production-mode profile e.g. `mvn clean package -Pproduction-mode` (tested a war build that it works as expected on tomcat 8.5)

**Comment by iatomic** [comment]
we have gone through all those motions already and neither worked. 
the flow-server-proudction is just xml framnet having the servlet parameter set.
We een made sure our web.xml has it set properly. it is still not working....

**Comment by caalador** [comment]
So not even giving it as a System Parameter works?
What's then different in the setup when comparing against the project base ?

**Comment by iatomic** [comment]
I think something might be overring it somehow...we are looking into it right now.

**Comment by Joe32** [comment]
In application.properties try vaadin.productionMode=true instead of vaadin.servlet.productionMode=true.
Second one is for vaadin8. They say it in this discussion: https://vaadin.com/forum/thread/17218697/production-or-debug-mode
Btw does [project base with spring](https://vaadin.com/start/lts/project-base-spring) work without this modification of application.properties in IE11? It does not for me.

**Comment by caalador** [comment]
IE11 doesn't work without transpiled JS. 
Also transpilation is only done through the maven plugin and served in production mode.

The spring base should work if you start the server with `mvn spring-boot:run -Pproduction-mode` or alternatively `mvn spring-boot:run -D vaadin.productionMode=true`

**Comment by web-padawan** [comment]
Closing per above comment as resolved (and not really specific to this component).
